# Copyright Built On Envoy
# SPDX-License-Identifier: Apache-2.0
# The full text of the Apache license is available in the LICENSE file at
# the root of the repo.

# This file must be in sync with .testcoverage.yaml that can be used locally.

codecov:
  # We build and upload only a single coverage file, so we don't need to wait for other CI
  # jobs to complete for us to see the coverage results
  require_ci_to_pass: false

flags:
  cli:
    paths:
      - cli
  extensions:
    paths:
      - extensions

coverage:
  status:
    project:
      cli:
        flags:
          - cli
        target: auto
        threshold: 5%
      extensions:
        flags:
          - extensions
        target: auto
        threshold: 5%
    patch:
      cli:
        flags:
          - cli
        target: auto
        only_pulls: true
        threshold: 5%
      extensions:
        flags:
          - extensions
        target: auto
        only_pulls: true
        threshold: 5%

# Do not add comments on PRs. The CI checks already link to the codecov reports
# and comments qre just noise.
comment: false

# Not interested in inline PR comments via github checks
github_checks:
  annotations: false

ignore:
  # Covered in integration tests.
  - cli/main.go
  - cli/internal/envoy/runner.go
  # These are test-only libraries.
  - cli/internal/testing/
  - extensions/**/standalone/main.go"
