# Copyright Built On Envoy
# SPDX-License-Identifier: Apache-2.0
# The full text of the Apache license is available in the LICENSE file at
# the root of the repo.

profile: ./out/go-test-coverage.out

threshold:
  # TODO: Increase these thresholds as we add more tests.
  file: 65
  package: 65
  total: 80

exclude:
  paths:
    - "standalone/main.go$"
