# Copyright Built On Envoy
# SPDX-License-Identifier: Apache-2.0
# The full text of the Apache license is available in the LICENSE file at
# the root of the repo.

header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: Built On Envoy
    content: |
      Copyright Built On Envoy
      SPDX-License-Identifier: Apache-2.0
      The full text of the Apache license is available in the LICENSE file at
      the root of the repo.
  paths-ignore:
    - out/
    # Ignore the CLI generated code
    - internal/extensions/manifests/
    - "**/go.mod"
    - "**/go.sum"
    - "**/*.md"
    - "**/*.tmpl"
    - "**/.gitignore"
    - "**/*.lock"
    - "**/*.pb.go"
    - "**/*.txt"
    - "**/Dockerfile.godym"
    - "**/Dockerfile.plugin"
    - .editorconfig
    - LICENSE
    - "**/coraza/rules/**"
    - "**/.claude/**"
    - "**/*.json"
    - "**/*.log"
    - "**/integration/coreruleset/**"
