# Copyright Built On Envoy
# SPDX-License-Identifier: Apache-2.0
# The full text of the Apache license is available in the LICENSE file at
# the root of the repo.

FROM scratch

ARG TARGETOS
ARG TARGETARCH

COPY ./test-${TARGETOS}-${TARGETARCH}.txt /files/
