// Copyright Built On Envoy
// SPDX-License-Identifier: Apache-2.0
// The full text of the Apache license is available in the LICENSE file at
// the root of the repo.

// This command exists beside the CLI so executable manifest examples are generated by running
// the same local extension and Envoy path users follow, with their output recorded for docs.
package main

import (
	"context"
	"flag"
	"fmt"
	"os"
	"os/signal"
	"strings"
	"syscall"
	"time"
)

type options struct {
	extensions   stringList
	boe          string
	envoyVersion string
	envoyPath    string
	check        bool
	timeout      time.Duration
}

type stringList []string

func (s *stringList) String() string { return strings.Join(*s, ",") }
func (s *stringList) Set(value string) error {
	*s = append(*s, value)
	return nil
}

func main() {
	os.Exit(run())
}

func run() int {
	var opts options
	flag.Var(&opts.extensions, "extension", "directory containing an extension manifest; may be repeated")
	flag.StringVar(&opts.boe, "boe", "", "path to the boe executable; built from this checkout when omitted")
	flag.StringVar(&opts.envoyVersion, "envoy-version", "1.38.0", "Envoy version to use")
	flag.StringVar(&opts.envoyPath, "envoy-path", "", "path to an Envoy binary")
	flag.BoolVar(&opts.check, "check", false, "fail if generated examples differ without writing files")
	flag.DurationVar(&opts.timeout, "timeout", 2*time.Minute, "total timeout for each example command (including retries) and Envoy startup")
	flag.Parse()

	if len(opts.extensions) == 0 {
		fmt.Fprintln(os.Stderr, "-extension is required")
		return 2
	}
	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer stop()
	if err := generate(ctx, &opts, os.Stdout, os.Stderr); err != nil {
		fmt.Fprintln(os.Stderr, err)
		return 1
	}
	return 0
}
