# Copyright Built On Envoy
# SPDX-License-Identifier: Apache-2.0
# The full text of the Apache license is available in the LICENSE file at
# the root of the repo.

FROM scratch

COPY ./manifest.yaml /manifest.yaml
COPY ./libcomposer.so.txt /libcomposer.so
