# Build the manager binary
FROM golang:1.25.6 AS builder

ARG PLUGIN_NAME

WORKDIR /workspace
COPY . .

RUN go mod download all
# Build go plugin
RUN go build -buildmode=plugin -o plugin.so ./${PLUGIN_NAME}

FROM scratch AS final

COPY --from=builder /workspace/plugin.so /
