# Build the manager binary
FROM golang:1.25.6 AS builder

WORKDIR /workspace
COPY . .

# Install necessary tools for cgo
RUN apt-get update
RUN apt-get install -y --no-install-recommends \
    ca-certificates wget git ssh netcat-openbsd gcc build-essential binutils binutils-gold

RUN go mod download all
# Build go shared library
RUN CGO_ENABLED=1 go build -buildmode=c-shared -o libcomposer.so main.go

FROM scratch AS final

COPY --from=builder /workspace/libcomposer* /
