// Copyright Built On Envoy
// SPDX-License-Identifier: Apache-2.0
// The full text of the Apache license is available in the LICENSE file at
// the root of the repo.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: config.proto

package goplugin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Configuration for the Go plugin loader.
type GoPlugin struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the dynamic module plugin
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Plugin configuration
	Config *structpb.Struct `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	// URL to fetch the plugin if it is a custom plugin
	Url string `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	// The composer will expect the loaded plugin's dependencies are subset of composer's
	// dependencies and no version conflict.
	// If set to true and then composer will reject any extensions that not meet the
	// above requirement strictly.
	// True by default.
	StrictCheck   *wrapperspb.BoolValue `protobuf:"bytes,4,opt,name=strict_check,json=strictCheck,proto3" json:"strict_check,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoPlugin) Reset() {
	*x = GoPlugin{}
	mi := &file_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoPlugin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoPlugin) ProtoMessage() {}

func (x *GoPlugin) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoPlugin.ProtoReflect.Descriptor instead.
func (*GoPlugin) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{0}
}

func (x *GoPlugin) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GoPlugin) GetConfig() *structpb.Struct {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *GoPlugin) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *GoPlugin) GetStrictCheck() *wrapperspb.BoolValue {
	if x != nil {
		return x.StrictCheck
	}
	return nil
}

var File_config_proto protoreflect.FileDescriptor

const file_config_proto_rawDesc = "" +
	"\n" +
	"\fconfig.proto\x12%builtonenvoy.extensions.core.goplugin\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\xa0\x01\n" +
	"\bGoPlugin\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12/\n" +
	"\x06config\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x06config\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12=\n" +
	"\fstrict_check\x18\x04 \x01(\v2\x1a.google.protobuf.BoolValueR\vstrictCheckB\xb0\x02\n" +
	")com.builtonenvoy.extensions.core.gopluginB\vConfigProtoP\x01Z>github.com/tetratelabs/built-on-envoy/extensions/core/goplugin\xa2\x02\x04BECG\xaa\x02%Builtonenvoy.Extensions.Core.Goplugin\xca\x02%Builtonenvoy\\Extensions\\Core\\Goplugin\xe2\x021Builtonenvoy\\Extensions\\Core\\Goplugin\\GPBMetadata\xea\x02(Builtonenvoy::Extensions::Core::Gopluginb\x06proto3"

var (
	file_config_proto_rawDescOnce sync.Once
	file_config_proto_rawDescData []byte
)

func file_config_proto_rawDescGZIP() []byte {
	file_config_proto_rawDescOnce.Do(func() {
		file_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_config_proto_rawDesc), len(file_config_proto_rawDesc)))
	})
	return file_config_proto_rawDescData
}

var file_config_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_config_proto_goTypes = []any{
	(*GoPlugin)(nil),             // 0: builtonenvoy.extensions.core.goplugin.GoPlugin
	(*structpb.Struct)(nil),      // 1: google.protobuf.Struct
	(*wrapperspb.BoolValue)(nil), // 2: google.protobuf.BoolValue
}
var file_config_proto_depIdxs = []int32{
	1, // 0: builtonenvoy.extensions.core.goplugin.GoPlugin.config:type_name -> google.protobuf.Struct
	2, // 1: builtonenvoy.extensions.core.goplugin.GoPlugin.strict_check:type_name -> google.protobuf.BoolValue
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_config_proto_init() }
func file_config_proto_init() {
	if File_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_config_proto_rawDesc), len(file_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_config_proto_goTypes,
		DependencyIndexes: file_config_proto_depIdxs,
		MessageInfos:      file_config_proto_msgTypes,
	}.Build()
	File_config_proto = out.File
	file_config_proto_goTypes = nil
	file_config_proto_depIdxs = nil
}
