// Copyright Built On Envoy
// SPDX-License-Identifier: Apache-2.0
// The full text of the Apache license is available in the LICENSE file at
// the root of the repo.

// Register all go-control-plane HTTP filter protos so that any @type URL
// used in a nativeHttpFilters.before typed_config resolves at runtime via
// protojson. The generated blank imports follow the pattern used by
// envoy-gateway (internal/xds/extensions).
//
//go:generate sh -c "printf '// Copyright Built On Envoy\n// SPDX-License-Identifier: Apache-2.0\n// The full text of the Apache license is available in the LICENSE file at\n// the root of the repo.\n\n// Code generated by go generate; DO NOT EDIT.\n\npackage envoy\n\nimport (\n' > extensions_gen.go && moddir=`go list -m -f '{{.Dir}}' github.com/envoyproxy/go-control-plane/envoy` && (cd \"${DOLLAR}moddir\" && go list ./extensions/filters/http/...) | awk '{printf \"\t_ \\\"%s\\\"\\n\", ${DOLLAR}0}' >> extensions_gen.go && printf ')\n' >> extensions_gen.go"

package envoy
