// Copyright Built On Envoy
// SPDX-License-Identifier: Apache-2.0
// The full text of the Apache license is available in the LICENSE file at
// the root of the repo.

package openai

import (
	"bytes"
	"encoding/json"
	"fmt"
	"strings"

	llm "github.com/tetratelabs/built-on-envoy/extensions/composer/llm-proxy/llm"
)

// strVal safely casts v to string, returning "" on failure.
func strVal(v any) string {
	s, _ := v.(string)
	return s
}

// OpenAI content part type constants.
const (
	openaiChatContentTypeText       = "text"
	openaiChatContentTypeImageURL   = "image_url"
	openaiChatContentTypeInputAudio = "input_audio"
	openaiChatContentTypeFile       = "file"
	openaiChatContentTypeRefusal    = "refusal"
)

// openaiChatUsage holds token-usage statistics returned in every response and
// in the final streaming chunk (when stream_options.include_usage is true).
type openaiChatUsage struct {
	PromptTokens     uint32 `json:"prompt_tokens"`     // tokens consumed by the input messages
	CompletionTokens uint32 `json:"completion_tokens"` // tokens generated by the model
	TotalTokens      uint32 `json:"total_tokens"`      // sum of prompt_tokens and completion_tokens
}

// openaiChatContentPartText is a plain-text content part used inside a message
// content array (type discriminator = "text").
type openaiChatContentPartText struct {
	Type string `json:"type"` // always "text"
	Text string `json:"text"` // the text content
}

// openaiChatContentPartImageURL is an image content part used inside a message
// content array (type discriminator = "image_url").
// URL accepts an https URL or a base64 data URI (data:image/...;base64,...).
// Detail controls the resolution used for vision processing; omit to let the
// model choose automatically.
type openaiChatContentPartImageURL struct {
	Type     string `json:"type"` // always "image_url"
	ImageURL struct {
		URL    string `json:"url"`
		Detail string `json:"detail,omitempty"` // resolution hint: "auto" | "low" | "high"
	} `json:"image_url"`
}

// openaiChatContentPartInputAudio is an audio content part used inside a message
// content array (type discriminator = "input_audio").
type openaiChatContentPartInputAudio struct {
	Type       string `json:"type"` // always "input_audio"
	InputAudio struct {
		Data   string `json:"data"`   // base64-encoded audio bytes
		Format string `json:"format"` // encoding format: "wav" | "mp3"
	} `json:"input_audio"`
}

// openaiChatContentPartFile is a file content part used inside a message content
// array (type discriminator = "file").
// Supply exactly one of FileID (a file previously uploaded via the Files API) or
// FileData (inline base64-encoded bytes). Filename guides MIME-type inference.
type openaiChatContentPartFile struct {
	Type string `json:"type"` // always "file"
	File struct {
		FileID   string `json:"file_id,omitempty"`   // ID of a file uploaded via the Files API
		FileData string `json:"file_data,omitempty"` // inline base64-encoded file bytes
		Filename string `json:"filename,omitempty"`  // filename hint used for MIME-type detection
	} `json:"file"`
}

// openaiChatContentPartRefusal is a refusal content part used inside a message
// content array (type discriminator = "refusal").
type openaiChatContentPartRefusal struct {
	Type    string `json:"type"`    // always "refusal"
	Refusal string `json:"refusal"` // the refusal text produced by the model
}

// openaiChatMessageParamAudio is the audio reference used inside an assistant
// message param when replaying a prior audio response in a multi-turn conversation.
// Only the ID is needed; the server resolves the full audio object from it.
type openaiChatMessageParamAudio struct {
	ID string `json:"id"` // ID from a prior openaiChatMessageAudio response
}

// openaiChatMessageParam is one message in the request messages array.
// Role must be one of "system", "developer", "user", "assistant", or "tool".
// "developer" replaces "system" on newer models for high-priority instructions.
//
// Content holds one of:
//   - string  – plain-text shorthand accepted for all roles
//   - []any   – array of typed content-part pointers for multimodal input:
//     |         *openaiChatContentPartText
//     |         *openaiChatContentPartImageURL
//     |         *openaiChatContentPartInputAudio
//     |         *openaiChatContentPartRefusal
//     |         *openaiChatContentPartFile
//   - nil     – omitted; valid on assistant messages that only carry ToolCalls
//
// Refusal and Audio are only valid on assistant-role messages and must mirror
// the values returned by a prior response when replaying conversation history.
// ToolCalls is only set on assistant-role messages when replaying prior model output.
// ToolCallID is only set on tool-role messages; it must match the ID in the
// corresponding assistant ToolCalls entry.
// Name optionally distinguishes participants that share the same role.
type openaiChatMessageParam struct {
	Name       string                       // optional participant name to distinguish senders with the same role
	Role       string                       // "system" | "developer" | "user" | "assistant" | "tool"
	Content    any                          // string, []any of content-part pointers, or nil
	ToolCallID string                       // ID of the tool call this message is answering (tool role only)
	Refusal    *string                      // refusal text from a prior assistant response (assistant role only)
	Audio      *openaiChatMessageParamAudio // reference to a prior audio response by ID (assistant role only)
	ToolCalls  []openaiChatToolCall         // tool invocations to replay (assistant role only)
}

func (m *openaiChatMessageParam) UnmarshalJSON(data []byte) error {
	var raw struct {
		Role       string                       `json:"role"`
		Content    any                          `json:"content,omitempty"`
		Refusal    *string                      `json:"refusal,omitempty"`
		Audio      *openaiChatMessageParamAudio `json:"audio,omitempty"`
		ToolCalls  []openaiChatToolCall         `json:"tool_calls,omitempty"`
		ToolCallID string                       `json:"tool_call_id,omitempty"`
		Name       string                       `json:"name,omitempty"`
	}
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}
	m.Role = raw.Role
	m.Refusal = raw.Refusal
	m.Audio = raw.Audio
	m.ToolCalls = raw.ToolCalls
	m.ToolCallID = raw.ToolCallID
	m.Name = raw.Name
	switch c := raw.Content.(type) {
	case string:
		m.Content = c
	case []interface{}:
		parts := make([]any, 0, len(c))
		for _, item := range c {
			part, err := unmarshalOpenAIContentPart(item)
			if err != nil {
				return err
			}
			parts = append(parts, part)
		}
		m.Content = parts
	}
	return nil
}

func (m openaiChatMessageParam) MarshalJSON() ([]byte, error) {
	raw := struct {
		Role       string                       `json:"role"`
		Content    any                          `json:"content,omitempty"`
		Refusal    *string                      `json:"refusal,omitempty"`
		Audio      *openaiChatMessageParamAudio `json:"audio,omitempty"`
		ToolCalls  []openaiChatToolCall         `json:"tool_calls,omitempty"`
		ToolCallID string                       `json:"tool_call_id,omitempty"`
		Name       string                       `json:"name,omitempty"`
	}{
		Role:       m.Role,
		Content:    m.Content,
		Refusal:    m.Refusal,
		Audio:      m.Audio,
		ToolCalls:  m.ToolCalls,
		ToolCallID: m.ToolCallID,
		Name:       m.Name,
	}
	return json.Marshal(raw)
}

// openaiChatMessageAudio holds the audio output embedded in a response message.
// Present only when the request included "audio" in the modalities list.
type openaiChatMessageAudio struct {
	ID         string `json:"id"`         // unique identifier for this audio output; used to reference it in follow-up turns
	Data       string `json:"data"`       // base64-encoded audio bytes
	ExpiresAt  int64  `json:"expires_at"` // Unix timestamp after which the server deletes the audio; cannot be referenced after this
	Transcript string `json:"transcript"` // text transcript of the generated audio
}

// openaiChatMessage is the assistant message returned inside a response choice.
// Role is always "assistant".
// Content contains the generated text, or nil when the response is tool calls
// only or an audio-only response (the wire value is null in those cases).
// Refusal is non-nil when the model declined to respond; it carries the refusal text.
// Audio is non-nil when an audio output modality was requested.
// ToolCalls lists the function invocations the model wants to perform.
type openaiChatMessage struct {
	Role      string                  `json:"role"`                 // always "assistant"
	Content   *string                 `json:"content"`              // generated text, or null when tool_calls or audio is the sole output
	Refusal   *string                 `json:"refusal,omitempty"`    // refusal message when the model declined to respond
	Audio     *openaiChatMessageAudio `json:"audio,omitempty"`      // audio output when the "audio" modality was requested
	ToolCalls []openaiChatToolCall    `json:"tool_calls,omitempty"` // function invocations the model is requesting
}

// unmarshalOpenAIContentPart converts a decoded JSON value (map[string]any)
// into a typed content-part pointer by inspecting the "type" field directly.
func unmarshalOpenAIContentPart(v any) (any, error) {
	m, ok := v.(map[string]any)
	if !ok {
		return nil, fmt.Errorf("openai: content part must be a JSON object, got %T", v)
	}
	t, _ := m["type"].(string)
	switch t {
	case openaiChatContentTypeText:
		p := &openaiChatContentPartText{Type: openaiChatContentTypeText}
		p.Text, _ = m["text"].(string)
		return p, nil
	case openaiChatContentTypeImageURL:
		p := &openaiChatContentPartImageURL{Type: openaiChatContentTypeImageURL}
		img, _ := m["image_url"].(map[string]any)
		p.ImageURL.URL, _ = img["url"].(string)
		p.ImageURL.Detail, _ = img["detail"].(string)
		return p, nil
	case openaiChatContentTypeInputAudio:
		p := &openaiChatContentPartInputAudio{Type: openaiChatContentTypeInputAudio}
		audio, _ := m["input_audio"].(map[string]any)
		p.InputAudio.Data, _ = audio["data"].(string)
		p.InputAudio.Format, _ = audio["format"].(string)
		return p, nil
	case openaiChatContentTypeRefusal:
		p := &openaiChatContentPartRefusal{Type: openaiChatContentTypeRefusal}
		p.Refusal, _ = m["refusal"].(string)
		return p, nil
	case openaiChatContentTypeFile:
		p := &openaiChatContentPartFile{Type: openaiChatContentTypeFile}
		f, _ := m["file"].(map[string]any)
		p.File.FileID, _ = f["file_id"].(string)
		p.File.FileData, _ = f["file_data"].(string)
		p.File.Filename, _ = f["filename"].(string)
		return p, nil
	default:
		// Unknown type: return the raw map so callers can inspect it.
		return m, nil
	}
}

// openaiChatToolCall is a tool invocation emitted by the model inside an
// assistant message. The ID must be echoed back as tool_call_id in the
// corresponding tool-role message so the model can match results to requests.
type openaiChatToolCall struct {
	ID       string `json:"id"`   // unique identifier for this invocation; echo as tool_call_id
	Type     string `json:"type"` // always "function"
	Function struct {
		Name      string `json:"name"`      // name of the function to call
		Arguments string `json:"arguments"` // model-generated JSON-encoded argument string
	} `json:"function"`
}

// openaiChatTool is a function tool definition included in the request.
// The model uses Description to decide when to invoke the tool and
// Parameters (a JSON Schema object) to generate correctly typed arguments.
type openaiChatTool struct {
	Type     string `json:"type"` // always "function"
	Function struct {
		Name        string `json:"name"`
		Description string `json:"description,omitempty"` // natural-language description shown to the model to guide tool selection
		Parameters  any    `json:"parameters,omitempty"`  // JSON Schema describing the function's accepted arguments
	} `json:"function"`
}

// openaiChatRequest is the OpenAI Chat Completions request body.
type openaiChatRequest struct {
	Model       string                   `json:"model"`                 // model ID, e.g. "gpt-4o"
	Messages    []openaiChatMessageParam `json:"messages"`              // ordered conversation history sent to the model
	Stream      bool                     `json:"stream,omitempty"`      // if true, responses are delivered as SSE chunks
	Tools       []openaiChatTool         `json:"tools,omitempty"`       // function tools the model may invoke
	ToolChoice  any                      `json:"tool_choice,omitempty"` // tool-selection policy: "auto" | "none" | "required" | {"type":"function","function":{"name":"..."}}
	MaxTokens   *int                     `json:"max_tokens,omitempty"`  // maximum output tokens; deprecated for reasoning models — prefer max_completion_tokens
	Temperature *float64                 `json:"temperature,omitempty"` // sampling temperature in [0, 2]; higher values produce more random output
	TopP        *float64                 `json:"top_p,omitempty"`       // nucleus-sampling probability cutoff in [0, 1]
}

// openaiChatResponse is the OpenAI Chat Completions non-streaming response body.
type openaiChatResponse struct {
	ID      string             `json:"id"`                // unique response identifier, prefixed "chatcmpl-"
	Object  string             `json:"object,omitempty"`  // always "chat.completion"
	Created int64              `json:"created,omitempty"` // Unix timestamp of when the response was created
	Model   string             `json:"model"`             // model that generated the response
	Choices []openaiChatChoice `json:"choices"`           // generated completions; one entry per n (default n=1)
	Usage   openaiChatUsage    `json:"usage"`             // token-usage statistics for the request
}

// openaiChatChoice is one generated completion inside a non-streaming response.
type openaiChatChoice struct {
	Index        int               `json:"index"`                   // 0-based completion index, corresponds to the n parameter
	Message      openaiChatMessage `json:"message"`                 // the assistant message generated for this choice
	FinishReason string            `json:"finish_reason,omitempty"` // reason generation stopped: "stop" | "length" | "tool_calls" | "content_filter"
}

// openaiChatChunk is a single SSE data event in an OpenAI streaming response.
// All chunks share the same ID. Usage is nil on every chunk except the last,
// and only when stream_options.include_usage was set to true in the request.
type openaiChatChunk struct {
	ID      string                  `json:"id"`                // shared identifier across all chunks of one response
	Object  string                  `json:"object,omitempty"`  // always "chat.completion.chunk"
	Created int64                   `json:"created,omitempty"` // Unix timestamp of when the stream started
	Model   string                  `json:"model,omitempty"`   // model producing the stream
	Choices []openaiChatChunkChoice `json:"choices"`           // incremental choice updates; usually one entry
	Usage   *openaiChatUsage        `json:"usage,omitempty"`   // token-usage statistics; only present on the final chunk
}

// openaiChatChunkChoice is one incremental choice update inside a streaming chunk.
type openaiChatChunkChoice struct {
	Index        int             `json:"index"`         // 0-based choice index
	Delta        openaiChatDelta `json:"delta"`         // incremental content update for this chunk
	FinishReason *string         `json:"finish_reason"` // null on all intermediate chunks; set to a stop reason on the final chunk
}

// openaiChatDelta carries the incremental content update inside a streaming chunk choice.
// Role is only populated on the very first chunk of a response.
// Content and ToolCalls are mutually exclusive within a single chunk.
type openaiChatDelta struct {
	Role      string               `json:"role,omitempty"`       // assistant role; only present on the first chunk
	Content   *string              `json:"content,omitempty"`    // incremental text token(s) for this chunk
	ToolCalls []openaiChatToolCall `json:"tool_calls,omitempty"` // incremental tool-call data; mutually exclusive with Content
}

// ---- llm.LLMRequest implementation ----

// openaiChatLLMRequest implements llm.LLMRequest for the OpenAI Chat Completions API.
type openaiChatLLMRequest struct {
	raw openaiChatRequest
}

func (r *openaiChatLLMRequest) GetModel() string         { return r.raw.Model }
func (r *openaiChatLLMRequest) IsStream() bool           { return r.raw.Stream }
func (r *openaiChatLLMRequest) GetMaxTokens() *int       { return r.raw.MaxTokens }
func (r *openaiChatLLMRequest) GetTemperature() *float64 { return r.raw.Temperature }
func (r *openaiChatLLMRequest) GetTopP() *float64        { return r.raw.TopP }

func (r *openaiChatLLMRequest) GetMessages() []llm.LLMMessage {
	return openaiChatMessagesToLLM(r.raw.Messages)
}

func (r *openaiChatLLMRequest) GetTools() []llm.LLMTool {
	return openaiChatToolsToLLM(r.raw.Tools)
}

func (r *openaiChatLLMRequest) GetToolChoice() *llm.LLMToolChoice {
	return openaiChatAnyToToolChoice(r.raw.ToolChoice)
}

// openaiChatAnyToToolChoice converts an OpenAI tool_choice value (decoded from JSON
// as any) to the canonical llm.LLMToolChoice. OpenAI uses strings ("auto", "none",
// "required") or {"type":"function","function":{"name":"..."}} objects.
// The object form is normalised to Type "tool" so the canonical representation
// is provider-agnostic.
func openaiChatAnyToToolChoice(v any) *llm.LLMToolChoice {
	switch tc := v.(type) {
	case string:
		if tc == "" {
			return nil
		}
		return &llm.LLMToolChoice{Type: tc}
	case map[string]any:
		// OpenAI's specific-tool object has type "function"; normalise to "tool".
		if strVal(tc["type"]) == llm.ToolTypeFunction {
			choice := &llm.LLMToolChoice{Type: llm.ToolChoiceFunction}
			if fn, ok := tc["function"].(map[string]any); ok {
				choice.Name = strVal(fn["name"])
			}
			return choice
		}
		return &llm.LLMToolChoice{Type: strVal(tc["type"])}
	}
	return nil
}

// llmToolChoiceToOpenAI converts a canonical llm.LLMToolChoice to the OpenAI wire format.
// Returns "auto", "none", "required" as strings; specific-tool as a map.
func llmToolChoiceToOpenAI(tc *llm.LLMToolChoice) any {
	if tc == nil {
		return nil
	}
	switch tc.Type {
	case llm.ToolChoiceFunction:
		return map[string]any{
			"type":     llm.ToolTypeFunction,
			"function": map[string]any{"name": tc.Name},
		}
	default:
		return tc.Type
	}
}

func (r *openaiChatLLMRequest) ToJSON() ([]byte, error) {
	return json.Marshal(r.raw)
}

// parseOpenAIRequest parses an OpenAI Chat Completions request body and returns
// an llm.LLMRequest with all extracted fields populated.
func parseOpenAIRequest(body []byte) (llm.LLMRequest, error) {
	var req openaiChatRequest
	if err := json.Unmarshal(body, &req); err != nil {
		return nil, err
	}
	return &openaiChatLLMRequest{raw: req}, nil
}

// ---- llm.LLMResponse implementation ----

// openaiChatLLMResponse implements llm.LLMResponse for the OpenAI Chat Completions API.
type openaiChatLLMResponse struct {
	raw openaiChatResponse
}

func (r *openaiChatLLMResponse) GetID() string    { return r.raw.ID }
func (r *openaiChatLLMResponse) GetModel() string { return r.raw.Model }

func (r *openaiChatLLMResponse) GetMessages() []llm.LLMMessage {
	return openaiChatChoicesToLLMMessages(r.raw.Choices)
}

func (r *openaiChatLLMResponse) GetStopReason() string {
	if len(r.raw.Choices) == 0 {
		return ""
	}
	return r.raw.Choices[0].FinishReason
}

func (r *openaiChatLLMResponse) GetUsage() llm.LLMUsage {
	return openaiChatUsageToLLM(r.raw.Usage)
}

func (r *openaiChatLLMResponse) ToJSON() ([]byte, error) {
	return json.Marshal(r.raw)
}

// parseOpenAIResponse parses an OpenAI Chat Completions response body and returns
// an llm.LLMResponse with all extracted fields populated.
func parseOpenAIResponse(body []byte) (llm.LLMResponse, error) {
	var resp openaiChatResponse
	if err := json.Unmarshal(body, &resp); err != nil {
		return nil, err
	}
	return &openaiChatLLMResponse{raw: resp}, nil
}

// ---- llm.LLMResponseChunk implementation ----

// openaiChatLLMResponseChunk implements llm.LLMResponseChunk for the OpenAI streaming API.
type openaiChatLLMResponseChunk struct {
	raw openaiChatChunk
}

func (c *openaiChatLLMResponseChunk) GetID() string    { return c.raw.ID }
func (c *openaiChatLLMResponseChunk) GetModel() string { return c.raw.Model }

func (c *openaiChatLLMResponseChunk) GetMessages() []llm.LLMMessage {
	if len(c.raw.Choices) == 0 {
		return nil
	}
	msgs := make([]llm.LLMMessage, 0, len(c.raw.Choices))
	for _, choice := range c.raw.Choices {
		msg := openaiChatDeltaToLLMMessage(choice.Delta)
		idx := choice.Index
		msg.Index = &idx
		msgs = append(msgs, *msg)
	}
	return msgs
}

func (c *openaiChatLLMResponseChunk) GetStopReason() string {
	if len(c.raw.Choices) == 0 || c.raw.Choices[0].FinishReason == nil {
		return ""
	}
	return *c.raw.Choices[0].FinishReason
}

func (c *openaiChatLLMResponseChunk) GetUsage() llm.LLMUsage {
	if c.raw.Usage == nil {
		return llm.LLMUsage{}
	}
	return openaiChatUsageToLLM(*c.raw.Usage)
}

// ToEvent encodes the chunk as a complete OpenAI SSE event: "data: <json>\n\n".
func (c *openaiChatLLMResponseChunk) ToEvent() ([]byte, error) {
	data, err := json.Marshal(c.raw)
	if err != nil {
		return nil, err
	}
	return append(append([]byte("data: "), data...), '\n', '\n'), nil
}

// parseOpenAIChunk parses a single data payload from an OpenAI streaming SSE response.
func parseOpenAIChunk(data []byte) (llm.LLMResponseChunk, error) {
	var chunk openaiChatChunk
	if err := json.Unmarshal(data, &chunk); err != nil {
		return nil, err
	}
	return &openaiChatLLMResponseChunk{raw: chunk}, nil
}

// ---- SSE parser ----

var openaiChatSSEDataPrefix = []byte("data: ")

// openaiChatSSEParser accumulates an OpenAI streaming SSE response into a final llm.LLMResponse.
type openaiChatSSEParser struct {
	buf   []byte
	done  bool
	id    string
	model string
	usage llm.LLMUsage
}

func newOpenAISSEParser() *openaiChatSSEParser {
	return &openaiChatSSEParser{}
}

func (a *openaiChatSSEParser) Feed(data []byte) ([]llm.LLMResponseChunk, error) {
	if a.done {
		return nil, nil
	}
	a.buf = append(a.buf, data...)
	return a.parseEvents()
}

func (a *openaiChatSSEParser) parseEvents() ([]llm.LLMResponseChunk, error) {
	var chunks []llm.LLMResponseChunk
	for {
		idx := bytes.IndexByte(a.buf, '\n')
		if idx < 0 {
			return chunks, nil
		}
		line := bytes.TrimSpace(a.buf[:idx])
		a.buf = a.buf[idx+1:]

		if !bytes.HasPrefix(line, openaiChatSSEDataPrefix) {
			continue
		}
		payload := bytes.TrimPrefix(line, openaiChatSSEDataPrefix)
		if bytes.Equal(payload, []byte("[DONE]")) {
			a.done = true
			return chunks, nil
		}
		chunk, err := parseOpenAIChunk(payload)
		if err != nil {
			return chunks, fmt.Errorf("llm-proxy: failed to parse OpenAI streaming chunk: %w", err)
		}
		if a.id == "" {
			a.id = chunk.GetID()
		}
		if a.model == "" {
			a.model = chunk.GetModel()
		}
		if u := chunk.GetUsage(); u != (llm.LLMUsage{}) {
			a.usage = u
		}
		chunks = append(chunks, chunk)
	}
}

func (a *openaiChatSSEParser) Finish() (llm.LLMResponse, error) {
	return &openaiChatLLMResponse{raw: openaiChatResponse{
		ID:    a.id,
		Model: a.model,
		Usage: openaiChatUsage{
			PromptTokens:     a.usage.InputTokens,
			CompletionTokens: a.usage.OutputTokens,
			TotalTokens:      a.usage.TotalTokens,
		},
	}}, nil
}

// ---- Factory ----

// openaiChatFactory implements llm.LLMFactory for the OpenAI Chat Completions API.
type openaiChatFactory struct{}

func (f *openaiChatFactory) ParseRequest(body []byte) (llm.LLMRequest, error) {
	return parseOpenAIRequest(body)
}

func (f *openaiChatFactory) ParseResponse(body []byte) (llm.LLMResponse, error) {
	return parseOpenAIResponse(body)
}

func (f *openaiChatFactory) ParseChunk(data []byte) (llm.LLMResponseChunk, error) {
	return parseOpenAIChunk(data)
}

func (f *openaiChatFactory) NewSSEParser() llm.SSEParser { return newOpenAISSEParser() }

func (f *openaiChatFactory) TransformRequest(req llm.LLMRequest) (llm.LLMRequest, error) {
	msgs := llmMsgsToOpenAI(req.GetMessages())
	tools := llmToolsToOpenAI(req.GetTools())
	raw := openaiChatRequest{
		Model:       req.GetModel(),
		Messages:    msgs,
		Stream:      req.IsStream(),
		MaxTokens:   req.GetMaxTokens(),
		Temperature: req.GetTemperature(),
		TopP:        req.GetTopP(),
	}
	if len(tools) > 0 {
		raw.Tools = tools
		raw.ToolChoice = llmToolChoiceToOpenAI(req.GetToolChoice())
	}
	return &openaiChatLLMRequest{raw: raw}, nil
}

func (f *openaiChatFactory) TransformResponse(resp llm.LLMResponse) (llm.LLMResponse, error) {
	msgs := resp.GetMessages()
	stopReason := resp.GetStopReason()
	choices := make([]openaiChatChoice, 0, len(msgs))
	for i, m := range msgs {
		oaMsg := openaiChatMessage{Role: m.Role}
		// Concatenate all text content parts into a plain string (OpenAI wire format).
		var textParts []string
		for _, part := range m.Content {
			if part.Type == llm.ContentPartTypeText {
				textParts = append(textParts, part.Text)
			}
		}
		if len(textParts) > 0 {
			s := strings.Join(textParts, "")
			oaMsg.Content = &s
		}
		if len(m.ToolCalls) > 0 {
			oaMsg.ToolCalls = llmToolCallsToOpenAI(m.ToolCalls)
		}
		choices = append(choices, openaiChatChoice{
			Index:        i,
			Message:      oaMsg,
			FinishReason: stopReason,
		})
	}
	u := resp.GetUsage()
	raw := openaiChatResponse{
		ID:    resp.GetID(),
		Model: resp.GetModel(),
		Usage: openaiChatUsage{
			PromptTokens:     u.InputTokens,
			CompletionTokens: u.OutputTokens,
			TotalTokens:      u.TotalTokens,
		},
		Choices: choices,
	}
	return &openaiChatLLMResponse{raw: raw}, nil
}

func (f *openaiChatFactory) TransformChunk(chunk llm.LLMResponseChunk) (llm.LLMResponseChunk, error) {
	raw := openaiChatChunk{
		ID:    chunk.GetID(),
		Model: chunk.GetModel(),
	}
	msgs := chunk.GetMessages()
	finishReason := chunk.GetStopReason()
	var choices []openaiChatChunkChoice
	if len(msgs) > 0 {
		for _, msg := range msgs {
			oaDelta := openaiChatDelta{Role: msg.Role}
			for _, part := range msg.Content {
				if part.Type == llm.ContentPartTypeText && part.Text != "" {
					s := part.Text
					oaDelta.Content = &s
					break
				}
			}
			if len(msg.ToolCalls) > 0 {
				oaDelta.ToolCalls = llmToolCallsToOpenAI(msg.ToolCalls)
			}
			idx := 0
			if msg.Index != nil {
				idx = *msg.Index
			}
			choice := openaiChatChunkChoice{Index: idx, Delta: oaDelta}
			if finishReason != "" {
				choice.FinishReason = &finishReason
			}
			choices = append(choices, choice)
		}
	} else {
		choice := openaiChatChunkChoice{Index: 0}
		if finishReason != "" {
			choice.FinishReason = &finishReason
		}
		choices = []openaiChatChunkChoice{choice}
	}
	raw.Choices = choices
	u := chunk.GetUsage()
	if u != (llm.LLMUsage{}) {
		raw.Usage = &openaiChatUsage{
			PromptTokens:     u.InputTokens,
			CompletionTokens: u.OutputTokens,
			TotalTokens:      u.TotalTokens,
		}
	}
	return &openaiChatLLMResponseChunk{raw: raw}, nil
}

// ---- Conversion helpers ----

// openaiChatMessagesToLLM converts OpenAI request messages to the canonical llm.LLMMessage slice.
func openaiChatMessagesToLLM(msgs []openaiChatMessageParam) []llm.LLMMessage {
	result := make([]llm.LLMMessage, 0, len(msgs))
	for _, msg := range msgs {
		llmMsg := llm.LLMMessage{Role: msg.Role, ToolCallID: msg.ToolCallID}

		// Decode tool calls from the top-level field into the canonical message.
		for i := range msg.ToolCalls {
			tc := &msg.ToolCalls[i]
			llmMsg.ToolCalls = append(llmMsg.ToolCalls, llm.LLMToolCall{
				ID:        tc.ID,
				Type:      tc.Type,
				Name:      tc.Function.Name,
				Arguments: tc.Function.Arguments,
			})
		}

		// Populate content parts by type-switching on the typed Content value.
		switch c := msg.Content.(type) {
		case string:
			if c != "" {
				llmMsg.Content = append(llmMsg.Content, llm.LLMContentPart{Type: llm.ContentPartTypeText, Text: c})
			}
		case []any:
			for _, part := range c {
				switch p := part.(type) {
				case *openaiChatContentPartText:
					llmMsg.Content = append(llmMsg.Content, llm.LLMContentPart{Type: llm.ContentPartTypeText, Text: p.Text})
				case *openaiChatContentPartImageURL:
					llmMsg.Content = append(llmMsg.Content, llm.LLMContentPart{Type: llm.ContentPartTypeImage, Image: &llm.LLMContentImage{URL: p.ImageURL.URL}})
				case *openaiChatContentPartInputAudio:
					llmMsg.Content = append(llmMsg.Content, llm.LLMContentPart{
						Type:  llm.ContentPartTypeAudio,
						Audio: &llm.LLMContentAudio{Data: p.InputAudio.Data, Format: p.InputAudio.Format},
					})
				case *openaiChatContentPartRefusal:
					llmMsg.Content = append(llmMsg.Content, llm.LLMContentPart{Type: llm.ContentPartTypeRefusal, Text: p.Refusal})
				case *openaiChatContentPartFile:
					llmMsg.Content = append(llmMsg.Content, llm.LLMContentPart{
						Type: llm.ContentPartTypeFile,
						File: &llm.LLMContentFile{FileID: p.File.FileID, FileData: p.File.FileData, Filename: p.File.Filename},
					})
				}
			}
		}

		result = append(result, llmMsg)
	}
	return result
}

// openaiChatToolsToLLM converts OpenAI tool definitions to canonical llm.LLMTool values.
func openaiChatToolsToLLM(tools []openaiChatTool) []llm.LLMTool {
	result := make([]llm.LLMTool, 0, len(tools))
	for _, t := range tools {
		result = append(result, llm.LLMTool{
			Type:        llm.ToolTypeFunction,
			Name:        t.Function.Name,
			Description: t.Function.Description,
			Parameters:  t.Function.Parameters,
		})
	}
	return result
}

// openaiChatChoicesToLLMMessages converts OpenAI choices to canonical llm.LLMMessage values.
func openaiChatChoicesToLLMMessages(choices []openaiChatChoice) []llm.LLMMessage {
	result := make([]llm.LLMMessage, 0, len(choices))
	for _, c := range choices {
		msg := llm.LLMMessage{Role: c.Message.Role}
		if c.Message.Content != nil && *c.Message.Content != "" {
			msg.Content = []llm.LLMContentPart{{Type: llm.ContentPartTypeText, Text: *c.Message.Content}}
		}
		if c.Message.Refusal != nil && *c.Message.Refusal != "" {
			msg.Content = append(msg.Content, llm.LLMContentPart{Type: llm.ContentPartTypeRefusal, Text: *c.Message.Refusal})
		}
		for _, tc := range c.Message.ToolCalls {
			msg.ToolCalls = append(msg.ToolCalls, llm.LLMToolCall{
				ID:        tc.ID,
				Type:      tc.Type,
				Name:      tc.Function.Name,
				Arguments: tc.Function.Arguments,
			})
		}
		result = append(result, msg)
	}
	return result
}

// openaiChatDeltaToLLMMessage converts an OpenAI streaming delta to a canonical llm.LLMMessage.
func openaiChatDeltaToLLMMessage(delta openaiChatDelta) *llm.LLMMessage {
	msg := &llm.LLMMessage{Role: delta.Role}
	if delta.Content != nil && *delta.Content != "" {
		msg.Content = []llm.LLMContentPart{{Type: llm.ContentPartTypeText, Text: *delta.Content}}
	}
	for _, tc := range delta.ToolCalls {
		msg.ToolCalls = append(msg.ToolCalls, llm.LLMToolCall{
			ID:        tc.ID,
			Type:      tc.Type,
			Name:      tc.Function.Name,
			Arguments: tc.Function.Arguments,
		})
	}
	return msg
}

// openaiChatUsageToLLM converts an openaiChatUsage to a canonical llm.LLMUsage.
func openaiChatUsageToLLM(u openaiChatUsage) llm.LLMUsage {
	return llm.LLMUsage{
		InputTokens:  u.PromptTokens,
		OutputTokens: u.CompletionTokens,
		TotalTokens:  u.TotalTokens,
	}
}

// llmToolCallsToOpenAI converts canonical llm.LLMToolCall values to openaiChatToolCall values.
func llmToolCallsToOpenAI(calls []llm.LLMToolCall) []openaiChatToolCall {
	result := make([]openaiChatToolCall, 0, len(calls))
	for _, c := range calls {
		tc := llm.ToolTypeFunction
		if c.Type != "" {
			tc = c.Type
		}
		call := openaiChatToolCall{ID: c.ID, Type: tc}
		call.Function.Name = c.Name
		call.Function.Arguments = c.Arguments
		result = append(result, call)
	}
	return result
}

// llmMsgsToOpenAI converts canonical llm.LLMMessage values to OpenAI request message params.
func llmMsgsToOpenAI(msgs []llm.LLMMessage) []openaiChatMessageParam {
	result := make([]openaiChatMessageParam, 0, len(msgs))
	for _, msg := range msgs {
		oaMsg := openaiChatMessageParam{Role: msg.Role, ToolCallID: msg.ToolCallID}

		// Tool calls from the top-level field become the wire tool_calls array.
		if len(msg.ToolCalls) > 0 {
			oaMsg.ToolCalls = llmToolCallsToOpenAI(msg.ToolCalls)
		}

		var parts []any
		for _, part := range msg.Content {
			switch part.Type {
			case llm.ContentPartTypeRefusal:
				parts = append(parts, &openaiChatContentPartRefusal{Type: openaiChatContentTypeRefusal, Refusal: part.Text})
			case llm.ContentPartTypeImage:
				img := &openaiChatContentPartImageURL{Type: openaiChatContentTypeImageURL}
				if part.Image != nil {
					img.ImageURL.URL = part.Image.URL
				}
				parts = append(parts, img)
			case llm.ContentPartTypeAudio:
				audio := &openaiChatContentPartInputAudio{Type: openaiChatContentTypeInputAudio}
				if part.Audio != nil {
					audio.InputAudio.Data = part.Audio.Data
					audio.InputAudio.Format = part.Audio.Format
				}
				parts = append(parts, audio)
			case llm.ContentPartTypeFile:
				f := &openaiChatContentPartFile{Type: openaiChatContentTypeFile}
				if part.File != nil {
					f.File.FileID = part.File.FileID
					f.File.FileData = part.File.FileData
					f.File.Filename = part.File.Filename
				}
				parts = append(parts, f)
			default:
				parts = append(parts, &openaiChatContentPartText{Type: openaiChatContentTypeText, Text: part.Text})
			}
		}

		// Encode content: plain string for a single text part, typed array otherwise.
		if len(parts) == 1 {
			if t, ok := parts[0].(*openaiChatContentPartText); ok {
				oaMsg.Content = t.Text
			} else {
				oaMsg.Content = parts
			}
		} else if len(parts) > 0 {
			oaMsg.Content = parts
		}

		result = append(result, oaMsg)
	}
	return result
}

// llmToolsToOpenAI converts canonical llm.LLMTool values to OpenAI tool definitions.
func llmToolsToOpenAI(tools []llm.LLMTool) []openaiChatTool {
	result := make([]openaiChatTool, 0, len(tools))
	for _, t := range tools {
		tool := openaiChatTool{Type: llm.ToolTypeFunction}
		tool.Function.Name = t.Name
		tool.Function.Description = t.Description
		tool.Function.Parameters = t.Parameters
		result = append(result, tool)
	}
	return result
}

// NewFactory returns an llm.LLMFactory for the OpenAI Chat Completions API.
func NewFactory() llm.LLMFactory { return &openaiChatFactory{} }
