# Copyright Built On Envoy
# SPDX-License-Identifier: Apache-2.0
# The full text of the Apache license is available in the LICENSE file at
# the root of the repo.

.PHONY: clean
clean:
	rm -rf *.log
	rm -rf coreruleset
