// Copyright Built On Envoy
// SPDX-License-Identifier: Apache-2.0
// The full text of the Apache license is available in the LICENSE file at
// the root of the repo.

package cmd

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"text/template"
)

// Create is a command to create a new extension template.
type Create struct {
	Type string `help:"Type of the extension. Currently only 'composer' is supported." default:"composer" enum:"composer"`
	Name string `arg:"" help:"Name of the extension."`
	Path string `help:"Output directory for the extension. Defaults to the extension name." type:"path"`
}

// Run executes the create command.
func (c *Create) Run() error {
	if c.Path == "" {
		c.Path = c.Name
	}

	repoPath := filepath.Join(c.Path, c.Name)

	if err := os.MkdirAll(repoPath, 0755); err != nil {
		return fmt.Errorf("failed to create directory %s: %w", repoPath, err)
	}

	data := map[string]string{
		"Name": c.Name,
	}

	files := map[string]string{
		"plugin.go":     pluginGoTmpl,
		"manifest.yaml": manifestYamlTmpl,
		"Makefile":      makefileTmpl,
		"go.mod":        goModTmpl,
	}

	for name, tmpl := range files {
		path := filepath.Join(repoPath, name)
		f, err := os.Create(path)
		if err != nil {
			return fmt.Errorf("failed to create file %s: %w", path, err)
		}
		defer f.Close()

		t, err := template.New(name).Parse(tmpl)
		if err != nil {
			return fmt.Errorf("failed to parse template for %s: %w", name, err)
		}

		if err := t.Execute(f, data); err != nil {
			return fmt.Errorf("failed to execute template for %s: %w", name, err)
		}
		fmt.Printf("Created %s\n", path)
	}

	cmd := exec.Command("go", "mod", "tidy")
	cmd.Dir = repoPath
	if output, err := cmd.CombinedOutput(); err != nil {
		return fmt.Errorf("failed to run 'go mod tidy': %w\n%s", err, string(output))
	}

	return nil
}

const pluginGoTmpl = `package main

import (
	"github.com/envoyproxy/envoy/source/extensions/dynamic_modules/sdk/go/shared"
)

// This is the implementation of the HTTP filter.
type customHttpFilter struct {
	shared.EmptyHttpFilter
}

func (f *customHttpFilter) OnRequestHeaders(headers shared.HeaderMap, endStream bool) shared.HeadersStatus {
	// TODO: Implement your logic here.
	headers.Set("x-{{ .Name }}", "example")
	return shared.HeadersStatusContinue
}

func (f *customHttpFilter) OnRequestBody(body shared.BodyBuffer, endStream bool) shared.BodyStatus {
	return shared.BodyStatusContinue
}

func (f *customHttpFilter) OnRequestTrailers(trailers shared.HeaderMap) shared.TrailersStatus {
	return shared.TrailersStatusContinue
}

func (f *customHttpFilter) OnResponseHeaders(headers shared.HeaderMap, endStream bool) shared.HeadersStatus {
	return shared.HeadersStatusContinue
}

func (f *customHttpFilter) OnResponseBody(body shared.BodyBuffer, endStream bool) shared.BodyStatus {
	return shared.BodyStatusContinue
}

func (f *customHttpFilter) OnResponseTrailers(trailers shared.HeaderMap) shared.TrailersStatus {
	return shared.TrailersStatusContinue
}

// This is the factory for the HTTP filter.
type customHttpFilterFactory struct {
}

func (f *customHttpFilterFactory) Create(handle shared.HttpFilterHandle) shared.HttpFilter {
	return &customHttpFilter{}
}

// This is the configuration factory for the HTTP filter.
type customHttpFilterConfigFactory struct {
	shared.EmptyHttpFilterConfigFactory
}

func (f *customHttpFilterConfigFactory) Create(handle shared.HttpFilterConfigHandle, config []byte) (shared.HttpFilterFactory, error) {
	return &customHttpFilterFactory{}, nil
}

func WellKnownHttpFilterConfigFactories() map[string]shared.HttpFilterConfigFactory {
	return map[string]shared.HttpFilterConfigFactory{
		"{{ .Name }}": &customHttpFilterConfigFactory{},
	}
}
`

const manifestYamlTmpl = `name: {{ .Name }}
version: 0.0.1
categories:
  - Custom
author: Unknown
description: A custom composer extension.
longDescription: |
  A custom composer extension generated by boe create.
type: composer
composerVersion: "0.2.1"
tags:
  - go
  - http
  - filter
license: Apache-2.0
`

const makefileTmpl = `PLUGIN_NAME := {{ .Name }}
# Default data home layout for boe
DATA_HOME ?= $(HOME)/.local/share/boe

.PHONY: build
build:
	go build -buildmode=plugin -o $(PLUGIN_NAME).so .

.PHONY: install
install: build
	@echo "Installing $(PLUGIN_NAME)..."
	@version=$$(grep "version:" manifest.yaml | awk '{print $$2}'); \
	mkdir -p $(DATA_HOME)/extensions/goplugin/$(PLUGIN_NAME)/$$version; \
	cp $(PLUGIN_NAME).so $(DATA_HOME)/extensions/goplugin/$(PLUGIN_NAME)/$$version/plugin.so;
	@echo "Installed to $(DATA_HOME)/extensions/goplugin/$(PLUGIN_NAME)"

.PHONY: clean
clean:
	rm -f $(PLUGIN_NAME).so
`

const goModTmpl = `module {{ .Name }}

go 1.25.6

require (
	github.com/envoyproxy/envoy/source/extensions/dynamic_modules v0.0.0-00010101000000-000000000000
)

replace github.com/envoyproxy/envoy/source/extensions/dynamic_modules => github.com/wbpcode/envoy/source/extensions/dynamic_modules v0.0.0-20260128123219-3a5bf3e00204
`
