// Copyright Built On Envoy
// SPDX-License-Identifier: Apache-2.0
// The full text of the Apache license is available in the LICENSE file at
// the root of the repo.

package saml

import (
	"crypto/rand"
	"crypto/rsa"
	"crypto/x509"
	"crypto/x509/pkix"
	"encoding/hex"
	"encoding/json"
	"encoding/pem"
	"errors"
	"fmt"
	"math/big"
	"time"

	"github.com/tetratelabs/built-on-envoy/extensions/composer/pkg"
)

// Default configuration values.
const (
	defaultCookieName         = "_saml_session"
	defaultSessionDuration    = 8 * time.Hour
	defaultCookieSecure       = true
	defaultSubjectHeader      = "x-saml-subject"
	defaultSignAuthnRequests  = true
	defaultAllowedClockSkew   = 5 * time.Second
	defaultNameIDFormat       = "urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified"
	defaultDefaultRedirectURL = "/"
	defaultSLOPath            = "/saml/slo"
	defaultMetadataPath       = "/saml/metadata"
)

// Config holds the parsed configuration for the SAML filter.
type Config struct {
	// EntityID is the unique identifier (audience) of this Service Provider.
	EntityID string
	// ACSPath is the path that this filter will intercept for SAML ACS.
	ACSPath string
	// IDPMetadataXML is the inline IdP metadata XML string.
	IDPMetadataXML string

	// SPCert is the parsed SP certificate.
	SPCert *x509.Certificate
	// SPKey is the parsed SP private key.
	SPKey *rsa.PrivateKey
	// SPCertPEM is the raw PEM-encoded SP certificate (kept for metadata generation).
	SPCertPEM string
	// SPKeyPEM is the raw PEM-encoded SP private key.
	SPKeyPEM string
	// SPCertAutoGenerated indicates the SP certificate was auto-generated (not provided in config).
	SPCertAutoGenerated bool

	// Session configuration.
	CookieName       string
	SessionDuration  time.Duration
	CookieDomain     string
	CookieSecure     bool
	CookieSigningKey []byte

	// BypassPaths are paths that should bypass SAML authentication.
	BypassPaths []string
	// SubjectHeader is the header name to set with the authenticated user's NameID.
	SubjectHeader string
	// AttributeHeaders maps SAML attribute names to request header names.
	AttributeHeaders map[string]string

	// SignAuthnRequests controls whether AuthnRequests are signed.
	SignAuthnRequests bool
	// AllowedClockSkew is the allowed clock skew for assertion time validation.
	AllowedClockSkew time.Duration
	// NameIDFormat is the NameID format to request.
	NameIDFormat string
	// DefaultRedirectPath is the post-login redirect when RelayState is empty.
	DefaultRedirectPath string
	// SLOPath is the Single Logout path.
	SLOPath string
	// MetadataPath is the path to serve SP metadata.
	MetadataPath string
}

// rawConfig is the JSON-serializable representation of the configuration.
type rawConfig struct {
	EntityID       string         `json:"entity_id"`
	ACSPath        string         `json:"acs_path"`
	IDPMetadataXML pkg.DataSource `json:"idp_metadata_xml"`

	SPCertPEM *pkg.DataSource `json:"sp_cert_pem,omitempty"`
	SPKeyPEM  *pkg.DataSource `json:"sp_key_pem,omitempty"`

	Session *rawSessionConfig `json:"session,omitempty"`

	BypassPaths      []string          `json:"bypass_paths,omitempty"`
	SubjectHeader    string            `json:"subject_header,omitempty"`
	AttributeHeaders map[string]string `json:"attribute_headers,omitempty"`

	SignAuthnRequests   *bool  `json:"sign_authn_requests,omitempty"`
	AllowedClockSkew    string `json:"allowed_clock_skew,omitempty"`
	NameIDFormat        string `json:"name_id_format,omitempty"`
	DefaultRedirectPath string `json:"default_redirect_path,omitempty"`
	SLOPath             string `json:"slo_path,omitempty"`
	MetadataPath        string `json:"metadata_path,omitempty"`
}

type rawSessionConfig struct {
	CookieName       string `json:"cookie_name,omitempty"`
	Duration         string `json:"duration,omitempty"`
	CookieDomain     string `json:"cookie_domain,omitempty"`
	CookieSecure     *bool  `json:"cookie_secure,omitempty"`
	CookieSigningKey string `json:"cookie_signing_key,omitempty"`
}

// parseConfig parses the JSON configuration bytes into a Config struct.
// It validates required fields, parses PEM certificates and keys, and sets defaults.
func parseConfig(data []byte) (*Config, error) {
	var raw rawConfig
	if len(data) > 0 {
		if err := json.Unmarshal(data, &raw); err != nil {
			return nil, fmt.Errorf("failed to parse config JSON: %w", err)
		}
	}

	// Validate required string fields.
	if raw.EntityID == "" {
		return nil, errors.New("entity_id is required")
	}
	if raw.ACSPath == "" {
		return nil, errors.New("acs_path is required")
	}

	// Resolve IDPMetadataXML (required).
	if err := raw.IDPMetadataXML.Validate(); err != nil {
		return nil, fmt.Errorf("idp_metadata_xml: %w", err)
	}
	content, err := raw.IDPMetadataXML.Content()
	if err != nil || len(content) == 0 {
		return nil, fmt.Errorf("idp_metadata_xml: error %w or empty content", err)
	}
	idpMetaXML := string(content)

	// Resolve SPCertPEM and SPKeyPEM (optional pair; nil means absent, auto-generate).
	var spCertPEM, spKeyPEM string
	if raw.SPCertPEM != nil {
		if validateErr := raw.SPCertPEM.Validate(); validateErr != nil {
			return nil, fmt.Errorf("sp_cert_pem: %w", validateErr)
		}
		content, e := raw.SPCertPEM.Content()
		if e != nil {
			return nil, fmt.Errorf("sp_cert_pem: %w", e)
		}
		spCertPEM = string(content)
	}
	if raw.SPKeyPEM != nil {
		if validateErr := raw.SPKeyPEM.Validate(); validateErr != nil {
			return nil, fmt.Errorf("sp_key_pem: %w", validateErr)
		}
		content, e := raw.SPKeyPEM.Content()
		if e != nil {
			return nil, fmt.Errorf("sp_key_pem: %w", e)
		}
		spKeyPEM = string(content)
	}
	if (spCertPEM == "") != (spKeyPEM == "") {
		return nil, errors.New("sp_cert_pem and sp_key_pem must both be provided, or both omitted")
	}

	var cert *x509.Certificate
	var key *rsa.PrivateKey
	var autoGenerated bool

	if spCertPEM == "" {
		// Auto-generate an ephemeral SP certificate and key.
		cert, key, err = generateSelfSignedCertAndKey(raw.EntityID)
		if err != nil {
			return nil, fmt.Errorf("failed to auto-generate SP certificate and key: %w", err)
		}
		// Encode back to PEM for components that need the raw PEM form.
		spCertPEM = string(pem.EncodeToMemory(&pem.Block{Type: "CERTIFICATE", Bytes: cert.Raw}))
		spKeyPEM = string(pem.EncodeToMemory(&pem.Block{Type: "RSA PRIVATE KEY", Bytes: x509.MarshalPKCS1PrivateKey(key)}))
		autoGenerated = true
	} else {
		// Parse SP certificate.
		cert, err = parseCertificatePEM(spCertPEM)
		if err != nil {
			return nil, fmt.Errorf("failed to parse sp_cert_pem: %w", err)
		}

		// Parse SP private key.
		key, err = parsePrivateKeyPEM(spKeyPEM)
		if err != nil {
			return nil, fmt.Errorf("failed to parse sp_key_pem: %w", err)
		}
	}

	cfg := &Config{
		EntityID:            raw.EntityID,
		ACSPath:             raw.ACSPath,
		IDPMetadataXML:      idpMetaXML,
		SPCert:              cert,
		SPKey:               key,
		SPCertPEM:           spCertPEM,
		SPKeyPEM:            spKeyPEM,
		SPCertAutoGenerated: autoGenerated,

		// Defaults.
		CookieName:          defaultCookieName,
		SessionDuration:     defaultSessionDuration,
		CookieSecure:        defaultCookieSecure,
		SubjectHeader:       defaultSubjectHeader,
		SignAuthnRequests:   defaultSignAuthnRequests,
		AllowedClockSkew:    defaultAllowedClockSkew,
		NameIDFormat:        defaultNameIDFormat,
		DefaultRedirectPath: defaultDefaultRedirectURL,
		SLOPath:             defaultSLOPath,
		MetadataPath:        defaultMetadataPath,
		BypassPaths:         raw.BypassPaths,
		AttributeHeaders:    raw.AttributeHeaders,
	}

	// Apply session overrides.
	if raw.Session != nil {
		if err = applySessionConfig(cfg, raw.Session); err != nil {
			return nil, err
		}
	}

	// If no signing key was provided, generate a random one.
	if len(cfg.CookieSigningKey) == 0 {
		cfg.CookieSigningKey, err = generateRandomKey(32)
		if err != nil {
			return nil, fmt.Errorf("failed to generate cookie signing key: %w", err)
		}
	}

	// Apply optional field overrides.
	if raw.SubjectHeader != "" {
		cfg.SubjectHeader = raw.SubjectHeader
	}
	if raw.SignAuthnRequests != nil {
		cfg.SignAuthnRequests = *raw.SignAuthnRequests
	}
	if raw.AllowedClockSkew != "" {
		d, err := time.ParseDuration(raw.AllowedClockSkew)
		if err != nil {
			return nil, fmt.Errorf("failed to parse allowed_clock_skew: %w", err)
		}
		cfg.AllowedClockSkew = d
	}
	if raw.NameIDFormat != "" {
		cfg.NameIDFormat = raw.NameIDFormat
	}
	if raw.DefaultRedirectPath != "" {
		cfg.DefaultRedirectPath = raw.DefaultRedirectPath
	}
	if raw.SLOPath != "" {
		cfg.SLOPath = raw.SLOPath
	}
	if raw.MetadataPath != "" {
		cfg.MetadataPath = raw.MetadataPath
	}

	return cfg, nil
}

// applySessionConfig applies session configuration overrides.
func applySessionConfig(cfg *Config, raw *rawSessionConfig) error {
	if raw.CookieName != "" {
		cfg.CookieName = raw.CookieName
	}
	if raw.Duration != "" {
		d, err := time.ParseDuration(raw.Duration)
		if err != nil {
			return fmt.Errorf("failed to parse session duration: %w", err)
		}
		cfg.SessionDuration = d
	}
	if raw.CookieDomain != "" {
		cfg.CookieDomain = raw.CookieDomain
	}
	if raw.CookieSecure != nil {
		cfg.CookieSecure = *raw.CookieSecure
	}
	if raw.CookieSigningKey != "" {
		key, err := hex.DecodeString(raw.CookieSigningKey)
		if err != nil {
			return fmt.Errorf("failed to decode cookie_signing_key (expected hex): %w", err)
		}
		if len(key) != 32 {
			return fmt.Errorf("cookie_signing_key must be 32 bytes (64 hex chars), got %d bytes", len(key))
		}
		cfg.CookieSigningKey = key
	}
	return nil
}

// parseCertificatePEM parses a PEM-encoded X.509 certificate.
func parseCertificatePEM(pemStr string) (*x509.Certificate, error) {
	block, _ := pem.Decode([]byte(pemStr))
	if block == nil {
		return nil, errors.New("no PEM data found")
	}
	if block.Type != "CERTIFICATE" {
		return nil, fmt.Errorf("expected CERTIFICATE PEM block, got %s", block.Type)
	}
	return x509.ParseCertificate(block.Bytes)
}

// parsePrivateKeyPEM parses a PEM-encoded RSA private key.
// Supports both PKCS#1 (RSA PRIVATE KEY) and PKCS#8 (PRIVATE KEY) formats.
func parsePrivateKeyPEM(pemStr string) (*rsa.PrivateKey, error) {
	block, _ := pem.Decode([]byte(pemStr))
	if block == nil {
		return nil, errors.New("no PEM data found")
	}

	switch block.Type {
	case "RSA PRIVATE KEY":
		return x509.ParsePKCS1PrivateKey(block.Bytes)
	case "PRIVATE KEY":
		key, err := x509.ParsePKCS8PrivateKey(block.Bytes)
		if err != nil {
			return nil, err
		}
		rsaKey, ok := key.(*rsa.PrivateKey)
		if !ok {
			return nil, errors.New("PKCS#8 key is not an RSA key")
		}
		return rsaKey, nil
	default:
		return nil, fmt.Errorf("unsupported PEM block type %q (expected RSA PRIVATE KEY or PRIVATE KEY)", block.Type)
	}
}

// generateRandomKey generates a random key of the specified length.
func generateRandomKey(length int) ([]byte, error) {
	key := make([]byte, length)
	if _, err := rand.Read(key); err != nil {
		return nil, err
	}
	return key, nil
}

// generateSelfSignedCertAndKey generates an ephemeral self-signed certificate and RSA private key.
// The certificate is valid for 10 years with a random 128-bit serial number.
func generateSelfSignedCertAndKey(cn string) (*x509.Certificate, *rsa.PrivateKey, error) {
	key, err := rsa.GenerateKey(rand.Reader, 2048)
	if err != nil {
		return nil, nil, fmt.Errorf("failed to generate RSA key: %w", err)
	}

	serialNumber, err := rand.Int(rand.Reader, new(big.Int).Lsh(big.NewInt(1), 128))
	if err != nil {
		return nil, nil, fmt.Errorf("failed to generate serial number: %w", err)
	}

	template := &x509.Certificate{
		SerialNumber: serialNumber,
		Subject:      pkix.Name{CommonName: cn},
		NotBefore:    time.Now().Add(-1 * time.Hour),
		NotAfter:     time.Now().Add(10 * 365 * 24 * time.Hour),
		KeyUsage:     x509.KeyUsageDigitalSignature | x509.KeyUsageKeyEncipherment,
	}

	certDER, err := x509.CreateCertificate(rand.Reader, template, template, &key.PublicKey, key)
	if err != nil {
		return nil, nil, fmt.Errorf("failed to create certificate: %w", err)
	}

	cert, err := x509.ParseCertificate(certDER)
	if err != nil {
		return nil, nil, fmt.Errorf("failed to parse certificate: %w", err)
	}

	return cert, key, nil
}

func (c *Config) String() string {
	cp := *c
	cp.SPCert = nil
	cp.SPKey = nil
	jsonBytes, _ := json.MarshalIndent(cp, "", "  ")
	return string(jsonBytes)
}
