// Copyright Built On Envoy
// SPDX-License-Identifier: Apache-2.0
// The full text of the Apache license is available in the LICENSE file at
// the root of the repo.

// Package saml implements a SAML SP filter for Envoy.
package saml

import (
	"sync"

	"github.com/envoyproxy/envoy/source/extensions/dynamic_modules/sdk/go/shared"
)

// samlMetrics holds metric IDs defined at config time, used at request time.
type samlMetrics struct {
	authnRequests          shared.MetricID
	hasAuthnRequests       bool
	assertionsValidated    shared.MetricID
	hasAssertionsValidated bool
	sessionsCreated        shared.MetricID
	hasSessionsCreated     bool
	sessionsValidated      shared.MetricID
	hasSessionsValidated   bool
}

// samlFilterConfig holds the parsed configuration and IdP metadata,
// shared across all filter instances.
type samlFilterConfig struct {
	config  *Config
	metrics *samlMetrics

	// idpMetadata holds the parsed IdP metadata. When inline XML is used, this is
	// populated at config time and is immutable. When idp_metadata_url is used, this
	// starts as nil and is lazily populated on the first request via HttpCallout.
	idpMetadata *IDPMetadata

	// The following fields are only used when idp_metadata_url is configured.
	// They coordinate the lazy fetch of IdP metadata across worker threads.

	// idpMetadataURL is the URL to fetch IdP metadata from.
	idpMetadataURL string
	// idpMetadataCluster is the Envoy cluster name for the HttpCallout.
	idpMetadataCluster string
	// mu protects idpMetadata, metadataFetching, and pendingRequests during lazy init.
	mu sync.Mutex
	// metadataFetching indicates whether a metadata fetch is already in progress.
	metadataFetching bool
	// pendingRequests holds filter instances waiting for metadata to become available.
	// When the fetch completes, each filter's auth flow is run and the request is
	// either continued to upstream or a local response is sent.
	pendingRequests []*samlHTTPFilter
}

// samlFilterFactory creates per-request filter instances.
type samlFilterFactory struct {
	shared.EmptyHttpFilterFactory
	cfg *samlFilterConfig
}

func (f *samlFilterFactory) Create(handle shared.HttpFilterHandle) shared.HttpFilter {
	return &samlHTTPFilter{handle: handle, cfg: f.cfg}
}

// HTTPFilterConfigFactory is the configuration factory for the SAML filter.
type HTTPFilterConfigFactory struct {
	shared.EmptyHttpFilterConfigFactory
}

// Create creates a new SAML filter instance.
func (f *HTTPFilterConfigFactory) Create(handle shared.HttpFilterConfigHandle, config []byte) (shared.HttpFilterFactory, error) {
	// Parse the JSON configuration.
	cfg, err := parseConfig(config)
	if err != nil {
		handle.Log(shared.LogLevelError, "saml: failed to parse config: %s", err.Error())
		return nil, err
	}
	handle.Log(shared.LogLevelInfo, "saml: parsed config for entity_id=%s, acs_path=%s", cfg.EntityID, cfg.ACSPath)
	if cfg.SPCertAutoGenerated {
		handle.Log(shared.LogLevelInfo, "saml: auto-generated ephemeral SP certificate and key (not provided in config)")
	}

	filterCfg := &samlFilterConfig{
		config:  cfg,
		metrics: &samlMetrics{},
	}

	if cfg.IDPMetadataXML != "" {
		// Inline mode: parse IdP metadata at config time.
		idpMeta, err := parseIDPMetadata([]byte(cfg.IDPMetadataXML))
		if err != nil {
			handle.Log(shared.LogLevelError, "saml: failed to parse idp metadata: %s", err.Error())
			return nil, err
		}
		handle.Log(shared.LogLevelInfo, "saml: parsed idp metadata for entity_id=%s, sso_url=%s", idpMeta.EntityID, idpMeta.SSOURL)
		filterCfg.idpMetadata = idpMeta
	} else {
		// URL mode: metadata will be fetched lazily on the first request via HttpCallout.
		filterCfg.idpMetadataURL = cfg.IDPMetadataURL
		filterCfg.idpMetadataCluster = cfg.IDPMetadataCluster
		handle.Log(shared.LogLevelInfo, "saml: idp metadata will be fetched from %s via cluster %s", cfg.IDPMetadataURL, cfg.IDPMetadataCluster)
	}

	// Define metrics.
	metrics := filterCfg.metrics
	if id, status := handle.DefineCounter("saml_authn_requests_total"); status == shared.MetricsSuccess {
		metrics.authnRequests = id
		metrics.hasAuthnRequests = true
	}
	if id, status := handle.DefineCounter("saml_assertions_validated_total", "result"); status == shared.MetricsSuccess {
		metrics.assertionsValidated = id
		metrics.hasAssertionsValidated = true
	}
	if id, status := handle.DefineCounter("saml_sessions_created_total"); status == shared.MetricsSuccess {
		metrics.sessionsCreated = id
		metrics.hasSessionsCreated = true
	}
	if id, status := handle.DefineCounter("saml_sessions_validated_total", "result"); status == shared.MetricsSuccess {
		metrics.sessionsValidated = id
		metrics.hasSessionsValidated = true
	}

	handle.Log(shared.LogLevelDebug, "saml: config: %s", cfg.String())

	return &samlFilterFactory{cfg: filterCfg}, nil
}

// WellKnownHttpFilterConfigFactories is used to load the plugin.
func WellKnownHttpFilterConfigFactories() map[string]shared.HttpFilterConfigFactory { //nolint:revive
	return map[string]shared.HttpFilterConfigFactory{
		"saml": &HTTPFilterConfigFactory{},
	}
}
