// Copyright Built On Envoy
// SPDX-License-Identifier: Apache-2.0
// The full text of the Apache license is available in the LICENSE file at
// the root of the repo.

// Package saml implements a SAML SP filter for Envoy.
package saml

import (
	"github.com/envoyproxy/envoy/source/extensions/dynamic_modules/sdk/go/shared"
)

// samlMetrics holds metric IDs defined at config time, used at request time.
type samlMetrics struct {
	authnRequests          shared.MetricID
	hasAuthnRequests       bool
	assertionsValidated    shared.MetricID
	hasAssertionsValidated bool
	sessionsCreated        shared.MetricID
	hasSessionsCreated     bool
	sessionsValidated      shared.MetricID
	hasSessionsValidated   bool
}

// samlFilterConfig holds the parsed configuration and IdP metadata,
// shared across all filter instances.
type samlFilterConfig struct {
	config      *Config
	idpMetadata *IDPMetadata
	metrics     *samlMetrics
}

// samlFilterFactory creates per-request filter instances.
type samlFilterFactory struct {
	shared.EmptyHttpFilterFactory
	cfg *samlFilterConfig
}

func (f *samlFilterFactory) Create(handle shared.HttpFilterHandle) shared.HttpFilter {
	return &samlHTTPFilter{handle: handle, cfg: f.cfg}
}

// HTTPFilterConfigFactory is the configuration factory for the SAML filter.
type HTTPFilterConfigFactory struct {
	shared.EmptyHttpFilterConfigFactory
}

// Create creates a new SAML filter instance.
func (f *HTTPFilterConfigFactory) Create(handle shared.HttpFilterConfigHandle, config []byte) (shared.HttpFilterFactory, error) {
	// Parse the JSON configuration.
	cfg, err := parseConfig(config)
	if err != nil {
		handle.Log(shared.LogLevelError, "saml: failed to parse config: %s", err.Error())
		return nil, err
	}
	handle.Log(shared.LogLevelInfo, "saml: parsed config for entity_id=%s, acs_path=%s", cfg.EntityID, cfg.ACSPath)
	if cfg.SPCertAutoGenerated {
		handle.Log(shared.LogLevelInfo, "saml: auto-generated ephemeral SP certificate and key (not provided in config)")
	}

	// Parse IdP metadata from the inline XML.
	idpMeta, err := parseIDPMetadata([]byte(cfg.IDPMetadataXML))
	if err != nil {
		handle.Log(shared.LogLevelError, "saml: failed to parse idp metadata: %s", err.Error())
		return nil, err
	}
	handle.Log(shared.LogLevelInfo, "saml: parsed idp metadata for entity_id=%s, sso_url=%s", idpMeta.EntityID, idpMeta.SSOURL)

	// Define metrics.
	metrics := &samlMetrics{}
	if id, status := handle.DefineCounter("saml_authn_requests_total"); status == shared.MetricsSuccess {
		metrics.authnRequests = id
		metrics.hasAuthnRequests = true
	}
	if id, status := handle.DefineCounter("saml_assertions_validated_total", "result"); status == shared.MetricsSuccess {
		metrics.assertionsValidated = id
		metrics.hasAssertionsValidated = true
	}
	if id, status := handle.DefineCounter("saml_sessions_created_total"); status == shared.MetricsSuccess {
		metrics.sessionsCreated = id
		metrics.hasSessionsCreated = true
	}
	if id, status := handle.DefineCounter("saml_sessions_validated_total", "result"); status == shared.MetricsSuccess {
		metrics.sessionsValidated = id
		metrics.hasSessionsValidated = true
	}

	filterCfg := &samlFilterConfig{
		config:      cfg,
		idpMetadata: idpMeta,
		metrics:     metrics,
	}

	handle.Log(shared.LogLevelDebug, "saml: config: %s", cfg.String())

	return &samlFilterFactory{cfg: filterCfg}, nil
}

// WellKnownHttpFilterConfigFactories is used to load the plugin.
func WellKnownHttpFilterConfigFactories() map[string]shared.HttpFilterConfigFactory { //nolint:revive
	return map[string]shared.HttpFilterConfigFactory{
		"saml": &HTTPFilterConfigFactory{},
	}
}
