# Copyright Built On Envoy
# SPDX-License-Identifier: Apache-2.0
# The full text of the Apache license is available in the LICENSE file at
# the root of the repo.

name: Website

on:
  push:
    branches:
      - main
      - release-**
  pull_request:
    branches:
      - main
      - release-**

env:
  GOPROXY: https://proxy.golang.org

jobs:
  changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            website:
              - 'website/**'
              - 'cli/cmd/**'
              - 'extensions/manifest.schema.json'
              - 'extensions/**/manifest.yaml'
          predicate-quantifier: some  # Make the filters be OR-ed
          token: "" # don't use github api
    outputs:
      website: ${{ steps.changes.outputs.website }}

  website:
    needs: changes
    if: ${{ needs.changes.outputs.website == 'true' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./website
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - uses: actions/setup-go@v5
        with:
          go-version-file: cli/go.mod
          cache-dependency-path: cli/go.sum
      - run: make -C ../cli gen 
      - run: npm ci
      - run: npm run build

  # Aggregate all the required jobs and make it easier to customize CI required jobs
  website-checks:
    runs-on: ubuntu-latest
    needs:
      - website
    # We need this to run always to force-fail (and not skip) if any needed
    # job has failed. Otherwise, a skipped job will not fail the workflow.
    if: always()
    steps:
      - run: |
          echo "CI checks completed"
          [ "${{
              contains(needs.*.result, 'failure') ||
              contains(needs.*.result, 'cancelled')
            }}" == "false" ] || exit 1
